from typing import Dict, Any

def build_applicant_letter(
    customer: Dict[str, Any],
    result: Dict[str, Any],
) -> str:
    name = customer.get("name", "Customer")
    risk = result.get("overall_risk", "unknown")
    rate = result.get("interest_rate", "N/A")
    rec = result.get("recommendation", "needs_manual_review")

    if rec == "approve":
        decision_paragraph = (
            "We are pleased to inform you that your loan application has been assessed "
            "and found to be suitable based on our current evaluation criteria."
        )
    elif rec == "do_not_recommend":
        decision_paragraph = (
            "After careful review, we regret to inform you that we are unable to proceed "
            "with your loan application at this time."
        )
    else:
        decision_paragraph = (
            "Your loan application has undergone an initial assessment. "
            "At this stage, additional review is required before a final decision can be made."
        )

    rate_paragraph = ""
    if rec == "approve" and rate and rate.lower() != "unknown":
        rate_paragraph = (
            f"If you choose to proceed, the indicative interest rate applicable to your loan "
            f"would be {rate}, subject to final confirmation and standard terms and conditions."
        )

    letter = f"""\
Dear {name},

Thank you for your interest in our banking products and for submitting your loan application.

{decision_paragraph}

Based on our assessment, your application falls within a {risk.capitalize()} Risk profile.
{rate_paragraph}

Please note that this assessment is conducted in accordance with our internal credit evaluation
policies and prevailing regulatory requirements. Final loan approval, terms, and conditions
remain subject to verification and completion of any outstanding requirements.

Should you have any questions or require further clarification, please do not hesitate to
contact our customer service team. We appreciate the opportunity to serve you.

Yours sincerely,

Credit Risk Assessment Team  
[Bank Name]  
(This letter was generated by an automated assessment system and is subject to review.)
"""
    return "\n".join([line.rstrip() for line in letter.splitlines()])
